# Aula 12 – Introdução ao Pandas

Objetivo: compreender o que é o pacote Pandas, para que serve, o que é um objeto do tipo Series do Pandas e como utilizar os recursos dessa biblioteca no ramo do machine learning e ciência de dados.
- https://didatica.tech/curso-de-python-para-machine-learning-e-ciencia-de-dados-gratuito/

In [1]:
import pandas as pd

# Dicionário com listas:
alunos = {'Nome':['Ricardo', 'Pedro', 'Roberto', 'carlos'],
         'Nota':[4, 7, 5.5, 9],
         'Aprovado':['Não', 'Sim', 'Não', 'sim']}

In [2]:
# Transformar o dicionário em dataframe:
dataframe = pd.DataFrame(alunos)

In [3]:
print(dataframe)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   carlos   9.0      sim


In [4]:
dataframe.head()

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   carlos   9.0      sim

In [5]:
# Cria um array com indices - unidiemnsional:
objeto1 = pd.Series([2, 6, 9, 10, 5])
print(objeto1)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [6]:
# Array multidimensional:
import numpy as np
array1 = np.array([2, 6, 9, 10, 5])
print(array1)

[ 2  6  9 10  5]


In [7]:
array2 = np.array([(2, 6, 9, 10, 5), (6, 12, 2, 9, 10)])
print(array2)

[[ 2  6  9 10  5]
 [ 6 12  2  9 10]]


In [8]:
# Transforma um Array1 em Série:
objeto2 = pd.Series(array1)
print(objeto2)

0     2
1     6
2     9
3    10
4     5
dtype: int32


In [9]:
# Transforma um Array2 em Série:
objeto3 = pd.Series(array2) # erro por ter mais de uma dimensão
print(objeto3)

Exception: Data must be 1-dimensional